### ISSUE TITLE
"You'll be expected to use Unity version 2019.3.0f6"

### ISSUE THREAD

**Issue by andybak** [adrian-miasik/unity-shaders#8]
Isn't it the version of URP that counts - not the Unity version?

And breakage between minor version numbers for any project that's not touching the internals is pretty unlikely.

I suspect this advice is much more restrictive than it needs to be.

**Comment by adrian-miasik** [comment]
Yeah, you're right. 
URP is what we mostly care about.

The [recent Universal RP documentation](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@8.1/manual/requirements.html) indicates we should at least be using `2019.3.0f3` but no higher than `2019.4.x` for compatibility reasons. You'll probably get away with other versions too though. I just wanted to make things simple, and tell people to run what I'm running on my end. 😅 
![image](https://user-images.githubusercontent.com/12757380/83342342-4d245700-a2bc-11ea-94a9-6b42a9f8f76f.png)

But yeah, forcing users to use a certain unity version is quite restrictive sounding. 
Here's my proposed release note change. Let me know if this is better:
> ~You'll be expected to use Unity version 2019.3.0f6~
Since we are on `Universal RP 7.1.8`, users should use a compatible Unity version. [Recent Universal RP documentation](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@8.1/manual/requirements.html) indicates a min of `2019.3.0f3` and a max of `2019.4.x` for compatibility.
![image](https://user-images.githubusercontent.com/12757380/83342342-4d245700-a2bc-11ea-94a9-6b42a9f8f76f.png)

**Comment by andybak** [comment]
That's a lot better. I find inexperienced users tend to stress about Unity versions and your original wording might have led people to assume they had to upgrade or downgrade unnecessarily.

**Comment by adrian-miasik** [comment]
Yeah I think that's a fair point. This way we don't confuse people and tell them to install yet another version of unity, when they might already have a compatible version.

I've updated the release notes appropriately. 
Marking as fixed; closing issue.

Thanks for flagging this @andybak 👍
